bazelbuild/rules_closure

third_party/phantomjs/BUILD

mktemp takes different arguments on OS (the template is required).
See http://ci.bazel.io/job/rules_closure/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/1/console.

Make build work on OS X

---

README.md

This change set introduces new flags to the closure_js_binary
rule that help with angular integration:
* --angular_pass
allows processing of @ngInject for dependency injection
* --export_local_property_definitions
allows referencing controller properties from angular views
More details on the recommended patterns for integrating the
closure compiler with angular can be found here:
https://google.github.io/styleguide/angularjs-google-style.html

Mention AngularJS in README

---

closure/repositories.bzl

We've been experiencing a lot of build flakiness and failed installs due
to BitBucket's Amazon S3 hosting returning a lot of "AccessDenied:
Request has expired" errors.
We're now mirroring as much as possible to a GCS bucket run by the Bazel
team. This should be much faster and more reliable, since it introduces
fewer points of failure. That means happy Closure Rules users. It also
eliminates the possibility that any system administrators will be crying
over the fact that our CI systems are hammering their servers for
dependencies.
Reviewer: @wolfgangmeyers

Mirror external files using Google Cloud Storage

---

third_party/phantomjs/phantomjs.sh

This fix failing test with bazel @HEAD.
Tested: bazel 0.2.1 and bazel @HEAD: bazel clean --expunge && bazel test ...

phantomjs wrapper: fix runfiles tree algorithm

---

.travis.yml
closure/repositories.bzl
closure/templates/closure_template_js_library.bzl

Fix Issue #9 and Issue #42
Upgrade travis builds to use bazel 0.2.2b.
Update project paths to use the "str(Label(...))" fix documented in Issue #9.
Implement missing should_generate_js_doc support.

Fix Issue #9 and Issue #42

---

closure/testing/closure_js_test.bzl
third_party/phantomjs/phantomjs.sh

Fix runfile path behavior
@jart I'm very new to bazel and rules_closure so this fix is likely suboptimal. I'm very open to feedback about cleaner implementations.

Fix Issue #19

---

README.md
closure/repositories.bzl

When trying to utilize the version override provided by 17619240422e5b076e784fee0c5da89ca31ffafc I was still doing a good amount of copy/pasting. (However, I could have been doing it wrong. If so, please let me know.)
With this change I am able to specify custom versions of any dependency with very minimal code.
Are you open to an idea like this? Does a better solution exist?

Expand closure_repositories() API for easy dependency version overrides

---

README.md
closure/compiler/closure_js_deps.bzl
closure/compiler/test/BUILD
closure/compiler/test/closure_js_deps/BUILD
closure/compiler/test/closure_js_deps/goblin.js
closure/compiler/test/closure_js_deps/hyperion.js
closure/private/defs.bzl

- Make `closure_js_deps` actually work.
- Breaking API change: We no longer generate the legacy deps.js file that includes the weird bazel directory names. We only generate the deps-runfiles.js file now.
- Regression tests.

Fix closure_js_deps and test it

---

closure/compiler/closure_js_deps.bzl
closure/compiler/closure_js_library.bzl
closure/compiler/test/BUILD
closure/library/BUILD
closure/private/defs.bzl
closure/testing/closure_js_test.bzl
closure/testing/test/BUILD

Many Closure Compiler passes generate synthetic code that calls functions in [base.js](https://github.com/google/closure-library/blob/master/closure/goog/base.js). I don't want users to shoot themselves in the foot wondering why their ES6 modules won't compile without a mysterious `//closure/library:base` dependency they aren't actually using. It's better off being linked by default.
In fact, we're going to remove the `//closure/library:base` rule entirely, since strict dependency checking can't be applied to it. This is because it's logically impossible to say `goog.require('goog')`.
The only downside to using this library by default is that binaries will be bloated with its contents when compiled in `debug = True` or `compilation_level = "WHITESPACE_ONLY"` mode.
Therefore, a …

Put Closure Library base.js in deps by default

---

README.md
closure/compiler/closure_js_binary.bzl
closure/compiler/closure_js_deps.bzl
closure/compiler/closure_js_library.bzl
closure/compiler/test/BUILD
closure/compiler/test/exports_and_entry_points/BUILD
closure/compiler/test/exports_and_entry_points/library.js
closure/compiler/test/exports_and_entry_points/library_goog.js
closure/compiler/test/exports_and_entry_points/program.js
closure/library/closure_library.BUILD
closure/private/defs.bzl
closure/testing/closure_js_test.bzl
closure/testing/test/arithmetic_es6typed.js
closure/testing/test/arithmetic_scope_test.js

I got rid of the `main` attribute and introduced `entry_points` and `dependency_mode`. These will make the behavior more similar to the Closure Compiler, except with better error messages and documentation.
PTAL @robfig @hochhaus

Change closure_js_binary() main to entry_points

---

closure/compiler/closure_js_binary.bzl
closure/compiler/closure_js_deps.bzl
closure/compiler/closure_js_library.bzl
closure/library/closure_library.BUILD
closure/private/defs.bzl
closure/stylesheets/closure_css_binary.bzl
closure/testing/closure_js_test.bzl

https://github.com/google/closure-library/wiki/Frequently-Asked-Questions#when-i-compile-with-type-checking-on-i-get-warnings-about-bad-type-annotation-unknown-type-from-closure-library-files

Add deps.js to forward-declare closure-library types

---

README.md
closure/repositories.bzl
protobuf/BUILD
protobuf/closure_proto_js_library.bzl
protobuf/protobuf_js.BUILD
protobuf/test/BUILD
protobuf/test/example.js
protobuf/test/example.proto
protobuf/test/example_test.js
third_party/protobuf/BUILD

Is adding (closure-style) protocol buffer support to this library something that you are willing to consider?
My reasons for thinking this rule fits well here are that the proto3 JS output can be tightly coupled with `closure_js_library()` making protocol buffers trivial to use from JavaScript. If a `js_proto_library()` rule were added to the upstream protobuf repository it would likely not be integrated as well into the rules_closure ecosystem.
If you prefer this as a separate project it is easy for me to split it to out.

Add Closure-style JavaScript protocol buffer utilities.

---

README.md
closure/compiler/closure_js_binary.bzl
closure/compiler/test/BUILD
closure/compiler/test/exports_and_entry_points/BUILD
closure/compiler/test/strict_dependency_checking/BUILD
closure/private/defs.bzl
closure/stylesheets/test/BUILD
closure/templates/closure_template_java_library.bzl

I find myself adding certain boilerplate in nearly every `closure_js_binary()`. What do you think of setting up a few common defines (`goog.STRICT_MODE_COMPATIBLE`, `goog.soy.REQUIRE_STRICT_AUTOESCAPE`) and an output wrapper automatically?

Add common defines and output_wrapper to closure_js_binary()

---

README.md
closure/compiler/closure_js_binary.bzl
closure/private/defs.bzl
closure/repositories.bzl
closure/templates/BUILD
closure/templates/closure_template_js_library.bzl
closure/templates/incremental_dom_soy.BUILD
closure/templates/test/BUILD
closure/templates/test/greeter_idom.js
closure/templates/test/greeter_idom.soy
closure/templates/test/greeter_idom_test.js
third_party/incremental_dom/BUILD
third_party/incremental_dom/build.sh

FYI, the tests will fail until the idom *.tar.gz is mirrored.
I'm happy to make any fixes so please let me know what you spot that could be done better. I'm currently leaving this as a macro. I plan to convert closure_proto_library/closure_template_js_library to a rule as time permits in the future.

Add incremental-dom support to closure_template_js_library()

---

.travis.yml
closure/compiler/closure_js_library.bzl
closure/private/BUILD
closure/private/gensrcjar.sh
closure/private/java_proto_library.bzl
java/com/google/javascript/jscomp/BUILD
java/com/google/javascript/jscomp/JsChecker.java
java/com/google/javascript/jscomp/worker_protocol.proto

I'm following through on @damienmg's suggestion in #77.
This change significantly improves the performance of closure_js_library when `--strategy=JsChecker=worker` is passed to Bazel. Now it won't have to spin up a new JVM for every single library rule. This will be indispensable for projects that have one library rule for every js file. It also helps alleviates @pcj's concerns. However this only applies to library rules at the moment. I haven't implemented this for binary rules yet.
I copied some code from the Bazel codebase because I'm afraid to link against `@closure_tools//...` in the interest of hermeticism. I hope I'm doing things correctly.
CC: @philwo @hochhaus

Make JsChecker a Bazel worker

---

closure/compiler/closure_js_library.bzl

This is a new, upcoming requirement that helps Bazel decide whether an action can be executed via workers or not.

Add a "supports-workers" execution info tag to JsChecker.

---

closure/private/platform_http_file.bzl
closure/repositories.bzl
third_party/llvm/llvm/tools/clang/BUILD
third_party/phantomjs/BUILD

This commit introduces platform_http_file() which uses repository_rule()
to be smarter about which files we download. As a result, running
PhantomJS or clang-format no longer requires downloading the tarballs
for both Linux and Mac OS.

Don't download files for other platforms

---

closure/compiler/closure_js_binary.bzl

the default will still be VERBOSE, but can be overridden by adding "warning_level" to closure_js_binary, see #114

add warning_level argument to closure_js_binary

---

closure/repositories.bzl
closure/templates/BUILD
third_party/jssrc/BUILD

This provides the following types which are used in the soy js
protobuf support code:
proto.webutil.html.types.SafeHtmlProto
proto.webutil.html.types.SafeScriptProto
proto.webutil.html.types.SafeStyleProto
proto.webutil.html.types.SafeStyleSheetProto
proto.webutil.html.types.SafeUrlProto
proto.webutil.html.types.TrustedResourceUrlProto

Add safe-html-types  html.proto generation

---

closure/private/defs.bzl
closure/templates/closure_js_template_library.bzl

I couldn't refactor all of `closure_js_template_library()` into a rule because:
* `_closure_js_template_library()` needs to produce 1+ output(s) for which the file names are dynamically determined from the input file names. According to [the manual](https://bazel.io/versions/master/docs/skylark/rules.html#output-files) having a "output list type attribute" appears to be the only way to acomplish this with a rule.
* `closure_js_template_library()` needs to call `closure_js_library()` which is itself a rule. According to the [multiple rules](https://bazel.io/versions/master/docs/skylark/cookbook.html#macro-multiple-rules) section of the manual there is "no easy way to create a rule that directly uses the action of a native rule".
The reason for the partial refactoring is that my upcoming …

Refactor part of closure_js_template_library into a skylark rule

---

closure/testing/externs/phantom.js
closure/testing/phantomjs_harness.js
closure/testing/test/screenshot.js

The webserver module will bind to 0.0.0.0 if an IP address isn't specified. This caused problems with the Bazel sandbox.
Mr. Jenkins test this please

Ask PhantomJS webserver to listen on 127.0.0.1

---

closure/testing/test/BUILD

This genrule is broken by the sandbox because of a bug
in PhantomJS (ariya/phantomjs#13876).
Fixes bazelbuild/bazel#1715.

Set //closure/testing/test:fontdemo to local

---

closure/testing/phantomjs_test.bzl
closure/testing/test/BUILD

This will circumvent issue with Phantomjs failing in an OS X sandbox (ariya/phantomjs#13876)
All tests using phantomjs are currently failing. This just deactivate the sandbox for now
but might become a problem once we do remote execution in Bazel.
Tested on my mac laptop.

Set phantomjs_test to local

---

closure/templates/closure_js_template_library.bzl
closure/templates/test/greeter_idom_proto.js

Allows both incremental_dom and traditional soy targets to
share the same soy template files without a naming conflict
in the generated JS files.

Avoid generated file naming conflict

---

closure/private/defs.bzl

See an example [failure at HEAD](https://travis-ci.org/bazelbuild/rules_closure/jobs/161267965) vs a [success at bazel 0.3.0](https://travis-ci.org/bazelbuild/rules_closure/jobs/161267966) for more context.

Fix errors at bazel HEAD

---

closure/templates/test/BUILD
closure/templates/test/greeter_idom_fail.js
closure/templates/test/greeter_idom_fail_test.js
third_party/javascript/incremental_dom/build.sh

Add a target to ensure that missing required template @params result in a
compile time error. Without this bugfix (setting __esModule) in
incremental-dom-closure.js the compiler misses detection of required
parameters.

Fix incremental-dom-closure.js generation for 0.5.0

---

README.md
closure/compiler/closure_js_binary.bzl
closure/compiler/closure_js_deps.bzl
closure/compiler/closure_js_library.bzl
closure/compiler/test/BUILD
closure/compiler/test/closure_js_deps/BUILD
closure/compiler/test/closure_js_deps/hyperion2_bin_runfiles_test.sh
closure/compiler/test/closure_js_deps/hyperion2_lib_runfiles_test.sh
closure/compiler/test/extern.js
closure/compiler/test/extern_invoke.js
closure/compiler/test/extern_invoke_bad.js
closure/compiler/test/strict_dependency_checking/BUILD
closure/private/defs.bzl
closure/stylesheets/closure_css_library.bzl
closure/testing/BUILD
closure/testing/externs/BUILD
closure/testing/externs/phantom.js
closure/testing/phantomjs_harness.js
closure/testing/phantomjs_test.bzl
java/com/google/javascript/jscomp/JsChecker.java

This change deprecates the `externs` attribute of `closure_js_library`, removes all externs graph code. It also adds tests for externs functionality, and improves the code health of the externs we use in our codebase.
It's been possible for several years to list `@externs` files in the `srcs` attribute. So having a separate graph for externs doesn't really offer any advantages.

Deprecate externs attribute

---

.travis.yml

This is a variant of the travis file recently merged in rules_go.  `sudo=required` selects the *trusty beta* image that has jdk8.  It looks a bit off-putting, but I don't think it undermines the quality of the outcome.  If you don't use this, one has to explicity name `jdk = oraclejkd8`. That however conflicts with os=osx and forces one into a `matrix.include` pattern (which has it's own set of issues).

Add osx in travis build matrix.

---

.travis.yml
CONTRIBUTORS

Once ci.bazel.io put out a release candidate the initial osx travis script broke, demonstrating the importance of parsing the artifact name from the HTML page.  This change puts that logic back in (credit to @hochhaus) with pcregrep tweak for osx.

Resolve correct artifact for HEAD and release candidate.

---

closure/compiler/test/strict_dependency_checking/BUILD

In the future string representations of file object will be different and it will look like `<generated file path/to/file.txt>`, therefore the tests have been changed to check for this optional additional angular bracket.

Make rule tests compatible with the new string representations in Skylark

---

java/com/google/javascript/jscomp/JsCompilerRunner.java

Module resolution BROWSER appears to import a subset of the files supported by NODE
module resolution. The only difference being that when .js suffixes can be left off
of import statements and that non absolute/relative import statements will be imported
from a node_modules directory.

Use module resoltion NODE by default.

---

.bazelci/presubmit.yml
README.md

@jart Bazel is moving to a new CI system. We are checking in the configuration for our CI system so that we can test rules_closure after every Bazel change to ensure we don't break you. Cheers!

add new bazel ci configuration

---

closure/repositories.bzl
java/com/google/javascript/jscomp/BUILD
java/io/bazel/rules/closure/webfiles/BUILD
java/io/bazel/rules/closure/webfiles/server/BUILD
java/io/bazel/rules/closure/worker/BUILD
javatests/io/bazel/rules/closure/worker/BUILD

Closes #248.
This was deprecated with Bazel 0.8.0, which now uses
@com_google_protobuf instead.
This change will break users that use
closure_repositories(omit_com_google_protobuf_java=True), so I've
added a custom error message to make the resolution clearer.
Test Plan:
$ bazel test javatests/...
and confirm that the warning from #248 is gone.
Inspired-By: Rodrigo Queiro <overdrigzed@gmail.com>

Remove com_google_protobuf_java

---

closure/compiler/closure_js_binary.bzl
closure/compiler/closure_js_deps.bzl
closure/compiler/closure_js_library.bzl
closure/private/defs.bzl
closure/private/file_test.bzl
closure/private/files_equal_test.bzl
closure/stylesheets/closure_css_binary.bzl
closure/stylesheets/closure_css_library.bzl
closure/templates/closure_js_template_library.bzl
closure/testing/phantomjs_test.bzl
closure/webfiles/web_library.bzl

This makes rules_closure compatible with `--all_incompatible_changes`, best I can tell.

Remove deprecated Bazel features

---

java/io/bazel/rules/closure/BUILD

New version of turbine detects this as a layering violation (https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/515#f0057ef6-e13b-48f4-a7be-95488fcc52d6).

Fix strict deps warning

---

closure/compiler/test/strict_dependency_checking/BUILD

ES6 modules will soon no longer be considered "moochers" and dropped if not reachable from the entry points.

Specify entry_points for ES6 modules

---

closure/compiler/closure_js_aspect.bzl

This is a no-op for open-source since it affects only non-open sourced parts of the file.

Fix closure js aspect actions to always use param files

---

closure/compiler/closure_js_binary.bzl
closure/private/defs.bzl
java/com/google/javascript/jscomp/JsChecker.java

JsCompiler already supports zip input for a while and we are planning to use these rules for J2CL opensource.

Adds support for zip inputs as src.

---

closure/compiler/test/BUILD
java/com/google/javascript/jscomp/JsCompiler.java

closure_js_binary always advertises the sourcemap output however compiler
may not generate it (e.g. compilation_level=BUNLDLE). This patch
fixes that so the output is always generated by providing an emtpy one
if compiler didn't generate it.

Fix compilation_level=BUNDLE for closure_js_binary

---

java/io/bazel/rules/closure/webfiles/server/WebfilesServer.java
java/io/bazel/rules/closure/worker/Prefixes.java

Summary:
Prior to this commit, there was no way to prevent the webfiles server
from emitting ANSI color codes, even if the output is not to a TTY or
the terminal is not xterm. This commit teaches the webfiles server about
the `NO_COLOR` environment variable, which, if set to any value
(including empty) will prevent the emission of any ANSI codes.
See: <https://no-color.org/>
(Ideally, we would also default to no-color when stderr is not a TTY, as
Bazel itself does, but it looks getting that information precisely
requires dropping down into C++ land.)
Test Plan:
```
$ unset NO_COLOR
$ bazel run //closure/webfiles/test:raven 2>&1 |
> stdbuf -o0 grep 'Closure Rules' | xxd
00000000: 1b5b 3334 6d43 6c6f 7375 7265 2052 756c  .[34mClosure Rul
00000010: 6573 201b 5b31 6d57 6562 6669 6c65 7353  es …
```

web_library: respect NO_COLOR environment variable

---

.travis.yml
closure/protobuf/closure_proto_library.bzl

This migrates the provider containing information about protocol buffers from the old-style 'dep.proto' pattern to the new-style 'dep[ProtoInfo]' one.

Migrate protobuf info provider to new-style one.

---

java/com/google/javascript/jscomp/BUILD

This is no-op for open-source users.

Replace the dep for JsCompiler to ease running the repo inside Google.

---

closure/repositories.bzl

In: [1] the prerequisites were added to rules_closure for protobuf
upgrade to the version 3.7.0:
* Dependency on bazel_skylib
* Dependency on zlib
In this change the protobuf version is updated to 3.7.1.
[1] https://github.com/bazelbuild/rules_closure/pull/341

Update protobuf version to 3.7.1

---

WORKSPACE
closure/filegroup_external.bzl

Found this issue when building TensorFlow with `--incompatible_depset_is_not_iterable` and `--incompatible_depset_union`:
```
filegroup_external(
name = "org_python_license",
licenses = ["notice"],  # Python 2.0
sha256_urls = {
"7ca8f169368827781684f7f20876d17b4415bbc5cb28baa4ca4652f0dda05e9f": [
"https://mirror.bazel.build/docs.python.org/2.7/_sources/license.rst.txt",
"https://docs.python.org/2.7/_sources/license.rst.txt",
],
},
)
```

Fix incompatibility in closure/filegroup_external.bzl

---

closure/compiler/closure_js_binary.bzl

It's going to be deleted as all Soy templates are now strict.

Remove references to goog.soy.REQUIRE_STRICT_AUTOESCAPE

---

closure/templates/closure_java_template_library.bzl

Next version of the templates will start adding @Generated
which will need this dependency to compile.

Add JSR250 deps to closure templates deps

---

third_party/openssl/BUILD
third_party/openssl/openssl.cnf
third_party/phantomjs/BUILD
third_party/phantomjs/phantomjs.sh

Debian buster has changed /etc/ssl/openssl.cnf far enough that the
openssl built into phantomjs can't parse it.  I found this out by
stracing a test run and watching it access /etc/ssl/openssl.cnf.  We
want bazel to not rely on anything outside the sandbox.  The error that
is returned otherwise is:
140302110000960:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
140302110000960:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140302110000960:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf …

Use a sandboxed openssl.cnf file for phantomjs

---

WORKSPACE
javatests/io/bazel/rules/closure/WebpathTest.java

They behave identically, and the old names are being removed.
The new methods are available in Truth as of version 0.44, so update Truth to that version.

Migrate from is(Not)SameAs to is(Not)SameInstanceAs.

---

javatests/io/bazel/rules/closure/worker/testing/ProgramResult.java

This changes the format of the message, but all the information should still be there.

Migrate users from the old, deprecated Subject.fail* methods to the new Subject.fail* methods or, in some cases, to Subject.check.

---

README.md

The suggestion to run `:SoyParseInfoGenerator` is good, but is now broken (seemingly since stuff under `third_party/` was refactored). This just updates the command so it works again.

Fix `closure_java_template_library` suggestion

---

closure/compiler/closure_js_binary.bzl

```
Traceback (most recent call last):
File "/xxx/BUILD", line 117
closure_js_binary(name = 'yyy')
File "/private/var/tmp/_bazel_zzz/uuu/external/io_bazel_rules_closure/closure/compiler/closure_js_binary.bzl", line 43, in _impl
fail(("Unknown language %s try one of...))))
File "/private/var/tmp/_bazel_eustas/uuu/external/io_bazel_rules_closure/closure/compiler/closure_js_binary.bzl", line 45, in fail
", ".join(JS_LANGUAGES)
expected value of type 'sequence' for parameter 'elements', for call to method join(elements) of 'string'
```

Fix error reporting

---

closure/repositories.bzl

Add a Bazel rule for exposing zip file containing extern files used by the js compiler so tools depending on this repository can refer them.

Expose extern zip file from js compiler jar.

---

WORKSPACE
javatests/io/bazel/rules/closure/WebpathTest.java
javatests/io/bazel/rules/closure/worker/testing/ProgramResult.java

The type parameters are being removed from Subject.
Also, update to Truth 0.45, which makes this change possible by loosening the type parameters on Subject.Factory.

Extend raw Subject instead of supplying type parameters.

---

README.md
closure/templates/closure_js_template_library.bzl
closure/templates/test/BUILD
closure/templates/test/defs.soy

This also removes the vestigial `should_provide_require_soy_namespaces`
Fixes #381

closure_js_template_library: add `defs` attr as a pass-through to SoyToJsSrcCompiler

---

README.md

Some of the `bazel run` help commands in the README are out of date. This PR just fixes them so they work again.

Update helpful `bazel run` commands

---

javatests/io/bazel/rules/closure/webfiles/WebfilesValidatorProgramTest.java
javatests/io/bazel/rules/closure/webfiles/server/NetworkUtilsTest.java

The former is deprecated and replaced by the latter in Mockito 2. However, there is a
functional difference: ArgumentMatchers will reject `null` and check the type
if the matcher specified a type (e.g. `any(Class)` or `anyInt()`). `any()` will
remain to accept anything.
This reflects the internal changes 257191326 and 257195762

Migrate org.mockito.Matchers#any* to org.mockito.ArgumentMatchers

---

WORKSPACE
closure/defs.bzl
closure/repositories.bzl

This PR adds macros to closure/repositories.bzl to make rules_closure
more compliant with Bazel's Style Guide for Rules.
Working towards #421

Deprecate closure_repositories in favor of rules_closure_{dependencies,toolchains}

---

closure/templates/closure_js_template_library.bzl

User doesn't have control over these so it doesn't make
sense to have it enabled by default.
In the latest closure library release some method will be deprecated
and will cause breakage in most closure template targets without this
fix.

Suppress deprecated on soy generated code.

---

closure/protobuf_drop_java_7_compatibility.patch
closure/repositories.bzl

This is a workaround to suppress this annoying warning:
warning: -parameters is not supported for target value 1.7. Use 1.8 or later.
wenn building protobuf_java. The full story can be seen in this Bazel
issue: [1]. I tried hard to avoid the need for patching Protobuf on
fetch, by trying to remove Java 7 compatibility mode upstream, that was
rejected: [2]. Moreover, I tried hard and spent quite some time to fix
the problem in Bazel: [3], in non-invasive way, but this PR was as well
rejected. The next natural approach is to just patch the Protobuf source
during the fetch operation.
Needless to say, that the patching during the fetch has its own
disavdantages, that the patch would probably need to be updated on
every Protobuf upgrade. But what can you do? The developers are
complaining and …

Protobuf: Remove java 7 compatibility mode

---

closure/compiler/closure_js_binary.bzl

Restrict the set of allowed values for js_binary.dependency_mode and convert the deprecated STRICT/LOOSE into their preferred equivalents PRUNE/PRUNE_LEGACY, so we can eventually delete the former from Closure Compiler.

Validate and convert the dependency_mode attribute.

---

java/com/google/javascript/jscomp/JsCheckerPassConfig.java

This check cannot work properly in single-file mode, so we are dropping
support for calling it in single-file mode.

drop CheckMissingAndExtraRequires

---

closure/compiler/test/closure_js_deps/BUILD

This allows moving the file around a bit without breaking the test.

Loosen the test on goog.dom dependency

---

closure/compiler/test/closure_js_deps/BUILD
closure/compiler/test/exports_and_entry_points/BUILD
closure/compiler/test/strict_dependency_checking/BUILD
closure/protobuf/test/legacy/BUILD
closure/templates/test/BUILD
closure/testing/test/BUILD

Closure compiler will soon emit a linter warning on `goog.provide`, as
[`goog.module`](https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide#googmodule) is preferred for new code.

Suppress lintChecks on libraries using goog.provide

---

closure/compiler/closure_js_binary.bzl
closure/compiler/test/exports_and_entry_points/BUILD

Follow-up of #444 to remove the noisy warnings for people that don't set the attribute: https://buildkite.com/bazel/rules-closure-closure-compiler/builds/911#1461b437-91e6-453b-b3a7-7f193a31a209/201-213
This change also prints the name of the target and a buildozer fix in the error message to make migration easier.
//cc @tjgq

Replace default value of closure_js_binary#dependency_mode with PRUNE_LEGACY

---

README.md

We no-longer have to pretend that Starlark is Python,
GitHub linguists supports Starlark now.

Use Starlark syntax for code-snippets

---

README.md
closure/defs.bzl
closure/repositories.bzl

This was deprecated in favor of `rules_closure_dependencies()` and
`rules_closure_toolchains()` to be more consistent with other rules.
See https://docs.bazel.build/versions/master/skylark/deploying.html#dependencies
Updates #421

Remove deprecated closure_repositories() macro

---

closure/private/BUILD

This should never have been included in the public repository as it was only intended for legacy projects.

Remove ref to "transitionalforwarddeclarations.js"

---

java/com/google/javascript/jscomp/JsCompilerWarnings.java

Updates the leveling algorithm in JsCompilerWarnings to ignore any diagnostics it doesn't recognize, rather than assuming they're errors. Other guards are now given the chance to level such diagnostics. If there are no other guards, the the intrinsic level of the diagnostic is used.
This makes it possible to roll out new JSCompiler diagnostics without automatically breaking rules_closure users.

Stop leveling all diagnostics as ERROR by default

---

javatests/io/bazel/rules/closure/worker/testing/ProgramResult.java

The truth function `containsExactly` expects an Object... (array) and internally converts that to a List. By already passing-in a list, it will convert that list object into another list. 
Using `containsExactlyElementsIn` instead.

Fix incorrect usage of truth function `containsExactly`

---

java/com/google/javascript/jscomp/Diagnostics.java

The CheckMissingAndExtraRequires pass that this diagnostic referred to has been removed in favor of the
CheckMissingRequires pass, which can now be turned on via the more simply named "missingRequire" diagnostic group.

Remove last remaining reference to removed Closure Compiler diagnostic group.

---

closure/compiler/test/reports/BUILD

Current tests are asserting particular obfuscated names which is fragile.
Patch converts the test to use regex instead.

Make compiler report tests less fragile

---

closure/compiler/test/strict_dependency_checking/BUILD
java/com/google/javascript/jscomp/CheckStrictDeps.java

Currently the dependency checker errors when using relative imports of generated sources.
Added "es6_relative_imports_gen_srcs_bin" test to cover this case.

CheckStrictDeps: resolve module paths against js module roots

---

closure/compiler/closure_js_binary.bzl

This was accidentally left out of https://github.com/bazelbuild/rules_closure/pull/517.
We should probably use a depset to avoid calling to_list, but that's a larger refactor than I'm willing to do right now.

Include srcs in inputs to compiler action.

---

closure/protobuf/closure_js_proto_library.bzl

When the `error_on_name_conflict` option was introduced, the compiler produced one output file per message name, regardless of the message's namespace. So `foo.Message1` and `bar.Message1` would both yield a file named `message1.js`, and the compiler would overwrite this file and only keep the last generated file. The `error_on_name_conflict` option was added to allow a compile time check for duplicate file names instead of the compiler silently overwriting files.
This "last output file wins" behavior was removed in [https://github.com/protocolbuffers/protobuf/commit/0894e07536af88065d462cdc9d8e807c0723ef4d](https://github.com/protocolbuffers/protobuf/commit/0894e07536af88065d462cdc9d8e807c0723ef4d) (see js_generator.cc). Now, instead of overwriting existing files, the compiler will …

Remove obsolete proto compiler option

---

closure/compiler/closure_js_deps.bzl

Per #526, we should eventually delete the `closure_js_deps` rule, because
* it depends on a deprecated (and soon to be deleted) Closure Library script
* it generates `deps.js` files, which themselves are deprecated
* it sees very little usage (and in many of its usages, it's not necessary)
This PR deprecates it first.

Deprecate closure_js_deps.

---

closure/compiler/closure_js_library.bzl

This is a no-op. in older versions of Closure compiler this diagnostic
group is a strict subset of analyzerChecks. As of https://github.com/google/closure-compiler/commit/09e5fdf5af2a86f9ca92462b61c062224766646e,
the diagnostic is deprecated/slated for deletion and an alias of analyzerChecks.

Remove reference to analyzerChecksInternal

---

closure/private/defs.bzl
java/com/google/javascript/jscomp/JsChecker.java

This is a better alternative compared to pinning a specific version.  The compiler's documentation recommends against pinning, which causes surprising breakages when upstream code introduces newer language features.  This has passed an internal global presubmit.

Set default language_in to "STABLE"

---

closure/repositories.bzl

Unshaded jar ships its own version of protobuf that overrides the one defined in this project..

Use the not "unshaded" jar for closure compiler.

---

java/io/bazel/rules/closure/webfiles/server/listing.soy

This was requested by the soy team as dots are being cleaned up in the depot.

removing dots from soy template name

---

README.md

Closes https://github.com/bazelbuild/rules_closure/issues/552
Since we are not modifying any code, we can [skip ci].

Update Setup instructions to use 0.12.0 release

---

closure/webfiles/test/BUILD
closure/webfiles/web_library.bzl

Example (from test):
```
web_library(
name = "raven",
srcs = ["index.html"],
path = "/",
deps = [":stuff"],
host = "0.0.0.0",
port = "8080"
)
```
(Supersedes #557.)

Add attribute to web_library for host:port

---

javatests/io/bazel/rules/closure/WebpathTest.java

If these were wrong, the assumes would cause the remainder of the test to just not run, which is not desirable!

Use assertions rather than assumptions to verify known truths.

---

README.md
WORKSPACE
closure/defs.bzl
closure/repositories.bzl
closure/testing/BUILD
closure/testing/closure_js_test.bzl
closure/testing/gen_webtest_html.template
closure/testing/test/BUILD
closure/testing/web_test_repositories.bzl
closure/testing/webdriver_test.bzl
closure/webfiles/web_library.bzl
java/io/bazel/rules/closure/testing/BUILD
java/io/bazel/rules/closure/testing/TestDriver.java
java/io/bazel/rules/closure/testing/TestRunner.java
java/io/bazel/rules/closure/webfiles/server/WebfilesServer.java

Added the option to test with Selenium webdriver + rules_webtesting in `closure_js_test`.
* If `browsers` is specified, the tests will be run with Selenium webdriver/rules_webtesting.
* If `browsers` is not specified, there are no changes to the existing operation - the tests are run on phantomjs.
Add `setup_web_test_repositories()` to WORKSPACE to load all repositories needed:
```
load("@io_bazel_rules_closure//closure:defs.bzl", "setup_web_test_repositories")
setup_web_test_repositories(
chromium = True,
)
```
```
closure_js_test(
name = "simple_test",
timeout = "short",
srcs = ["simple_test.js"],
deps = [
"@com_google_javascript_closure_library//closure/goog/testing:asserts",
"@com_google_javascript_closure_library//closure/goog/testing:jsunit",
],
browsers = …
```

Support testing with webdriver and rules_webtesting

---

closure/testing/test/BUILD
third_party/llvm/llvm/tools/clang/BUILD
third_party/phantomjs/BUILD

darwin is a CPU that means macOS x86_64 so these selects were invalid for arm64 macs. Also I'm hoping to remove this cpu to reduce confusion which would also break this.

Fix macOS arm64 select() support

---

closure/templates/closure_js_template_library.bzl

- transitive_runtime_deps was an alias for transitive_runtime_jars
The fields were deprecated in 2021, and are dropped in Bazel@HEAD
Fixes https://github.com/bazelbuild/rules_closure/issues/578
CC Greenteam @Wyverald

Migrate usages of deprecated JavaInfo fields

---

java/io/bazel/rules/closure/testing/TestDriver.java

Wasm junit test running on mac system takes a bit long. the test has not finished yet when test driver detect the finish status, but it runs successfully in the end.

Modify test driver to wait until test finishes.

---

closure/private/file_test.bzl

Legacy struct providers have been deprecated by Bazel.

Replace legacy struct providers with modern ones

---

closure/webfiles/web_library.bzl

The "to_proto" method on Starlark structs is deprecated and shouldn't be used.
Instead, the proto module's "encode_text" function should be used.
(https://bazel.build/rules/lib/toplevel/proto)
It, along with "to_json", can be disabled in Bazel using the flag
--incompatible_struct_has_no_methods
The underlying implementation is the same, so there should be no observable
changes in final outputs.

Migrate uses of struct.to_proto

---

closure/compiler/closure_js_binary.bzl
closure/compiler/closure_js_library.bzl
closure/private/defs.bzl
closure/protobuf/closure_proto_library.bzl
closure/stylesheets/closure_css_library.bzl

This follows a more common provider approach where rules are
responsible for providing supplier to helper functions vs. helper
functions trying make it workaround with a mix of targets and
providers.
This also unbundles provider extraction from unfurl to remove
implicit and optional behaviors behind it.

Make create_closure_js_library work on providers.

---

closure/compiler/test/linting/BUILD
closure/compiler/test/linting/somemodule.js
java/com/google/javascript/jscomp/JsCheckerPassConfig.java
java/com/google/javascript/jscomp/JsCompilerRunner.java

- Add CheckTypeSummaryWarningsGuard to ignore errors from ijs files.
- Wrap modules in goog.modules for ijs files and sort them.
- Add input delimiters to help with debugging.

Fix incremental type checking for goog modules

---

closure/library/long.js

`Long.equals` accepts a nullable parameter, but will crash if you actually pass one. Instead we should always return null if `other` is null/undefined.
This is a backport of the internal version.

Add a null check to Long.equals

---

java/com/google/javascript/jscomp/JsCheckerPassConfig.java

The builder doesn't require passing the empty preprocessorSymbolTable & getAliasTransformationHandler arguments; we're also planning to remove getAliasTransformationHandler  completely in Closure Compiler as it's unused.

Move away from deprecated ScopedAliases pass constructor to new builder
