bazelbuild/rules_closure

- README.md
> Add concrete examples to README

- closure/compiler/closure_js_deps.bzl
This fixes #17 and causes the code to match the documentation.
@wolfgangmeyers
> Change closure_js_deps srcs to deps

- README.md
- closure/templates/closure_template_js_library.bzl
- closure/templates/test/BUILD
- closure/templates/test/greeter.js
- closure/templates/test/greeter.soy
- closure/templates/test/greeter_test.js
This fixes #28 and also adds a unit test for Soy.
Reviewer: @wolfgangmeyers
> Add Closure Library dep to Soy JS library

- README.md
- closure/compiler/closure_js_library.bzl
- closure/private/defs.bzl
- closure/repositories.bzl
- closure/stylesheets/BUILD
- closure/stylesheets/closure_css_binary.bzl
- closure/templates/BUILD
- closure/templates/closure_template_java_library.bzl
Closure Rules now works as an external dependency for my codebase. No copying necessary.
I'm declaring v0.0.2 tonight.
Attn: @damienmg @kchodorow @hochhaus @wolfgangmeyers
> Make Closure Rules work for my purposes

- closure/BUILD
- closure/private/files_equal_test.bzl
- closure/private/lines_sorted_test.bzl
- closure/repositories.bzl
I've also added maintenance documentation and enforcement tests. Furthermore we'll be using http:// for performance, since we're relying on checksums for security.
> Mirror Maven repositories

- closure/templates/test/BUILD
> closure_template_java_library: add simple file_test

- README.md
- closure/repositories.bzl
- third_party/llvm/llvm/tools/clang/BUILD
Thanks for your help with all of the extremely prompt reviews!
Let me know if you want this broken out differently.
> Add clang-format

- java/com/google/javascript/jscomp/JsChecker.java
@hochhaus please LGTM if this fixes #97.
> Make nonStandardJsDocs suppressable

- closure/library/BUILD
- closure/library/closure_library.BUILD
- closure/repositories.bzl
- java/com/google/javascript/jscomp/JsCheckerFirstPass.java
- java/com/google/javascript/jscomp/JsCheckerSecondPass.java
> Upgrade Closure Compiler and Library to v20160619

- closure/compiler/closure_js_binary.bzl
> Automatically set --assume_function_wrapper

- java/com/google/javascript/jscomp/JsChecker.java
> JsChecker: Remove deprecated use of setIdeMode

- closure/compiler/closure_js_binary.bzl
- closure/private/defs.bzl
- closure/repositories.bzl
- closure/templates/BUILD
- closure/templates/closure_js_template_library.bzl
- third_party/jssrc/BUILD
The extra files from jssrc (other than soyutils_usegoog.js) are used in a change that I will send shortly.
> Upgrade closure-templates to 2016-08-19

- .travis.yml
- closure/compiler/closure_js_binary.bzl
- closure/private/defs.bzl
Workaround of bazelbuild/bazel#1462
Fixed #130
> Make contains_file() work across bazel versions

- closure/repositories.bzl
- closure/stylesheets/test/BUILD
> Update to closure-stylesheets 1.4.0

- closure/compiler/closure_js_binary.bzl
- closure/compiler/closure_js_library.bzl
- closure/compiler/test/linting/BUILD
- java/com/google/javascript/jscomp/JsChecker.java
> Convert JsChecker WARNINGS to ERRORS

- .bazelci/presubmit.yml
- .travis.yml
- closure/compiler/closure_js_library.bzl
- closure/protobuf/closure_proto_library.bzl
- closure/testing/test/BUILD
> Remove flaky test on macOS

- closure/protobuf/test/BUILD
Fixes the google3, should be no-op for open-source.
> Add proper testing for closure proto rules

- closure/repositories.bzl
- java/org/jsoup/nodes/Html5Printer.java
1.11.3 contains a lot of bug fixes.
including https://github.com/jhy/jsoup/pull/901,
which allows using templates inside table.
> update jsoup to 1.11.3

- closure/defs.bzl
- closure/private/defs.bzl
- closure/stylesheets/closure_css_binary.bzl
- closure/stylesheets/closure_css_library.bzl
- closure/webfiles/web_library.bzl
- Explicitly re-export symbols
- Fix some of the issues related to --incompatible_depset_union 
Progress towards #311
> Cleanups for compatibility with future Bazel releases

- closure/compiler/closure_js_binary.bzl
- closure/compiler/closure_js_deps.bzl
- closure/compiler/closure_js_library.bzl
- closure/private/defs.bzl
- closure/protobuf/closure_proto_library.bzl
- closure/stylesheets/closure_css_binary.bzl
- closure/templates/closure_js_template_library.bzl
- closure/webfiles/web_library.bzl
> Fix incompatible_depset_is_not_iterable

- closure/compiler/closure_js_library.bzl
- closure/compiler/test/strict_dependency_checking/BUILD
- closure/repositories.bzl
- closure/testing/test/BUILD
- java/com/google/javascript/jscomp/Diagnostics.java
- java/com/google/javascript/jscomp/JsCheckerPassConfig.java
- java/com/google/javascript/jscomp/JsCompilerRunner.java
- java/io/bazel/rules/closure/webfiles/server/WebfilesServer.java
- java/io/bazel/rules/closure/worker/Prefixes.java
This also push internal changes to Java files since some of
these changes were done to make rules_closure compatible
with the Closure compiler.
> Upgrade closure compiler to latest release.

- closure/repositories.bzl
- closure/templates/closure_js_template_library.bzl
- closure/templates/soy_jssrc.BUILD
And remove no longer necessary shouldProvideRequireSoyNamespaces flag
> Upgrade soy dependency

- closure/compiler/closure_js_binary.bzl
- closure/compiler/closure_js_deps.bzl
- closure/compiler/closure_js_library.bzl
- closure/private/defs.bzl
- closure/testing/phantomjs_test.bzl
- closure/webfiles/web_library.bzl
Fix violations of `--incompatible_depset_union`
Fixes #345
> Cleanup some of the depsets

- closure/testing/test/BUILD
This  test is already commented the target is marked as local
> Comment out rest of the fontdemo

- javatests/io/bazel/rules/closure/worker/testing/ProgramResult.java
> Instead of calling Subject.actual(), store the actual value in a field, and read that.

- WORKSPACE
- javatests/io/bazel/rules/closure/webfiles/BUILD
- javatests/io/bazel/rules/closure/webfiles/server/BUILD
- javatests/io/bazel/rules/closure/worker/BUILD
> Update Mockito to 3.0.0

- closure/repositories.bzl
Context: https://github.com/bazelbuild/bazel/issues/10270
> Mirror all http_archives in third_party_repositories.bzl.

- closure/repositories.bzl
This should fix https://github.com/bazelbuild/bazel/issues/10595
Context, https://support.sonatype.com/hc/en-us/articles/360041287334
> Change http to https for Maven sources

- closure/compiler/test/BUILD
- closure/repositories.bzl
Changes in source maps come from the change: https://github.com/google/closure-compiler/commit/1a88c4ad0e21a6a31a672ba8bb621a22ea6dbce0
> Update closure compiler version to v20200614

- closure/repositories.bzl
- closure/templates/test/greeter_proto.soy
Update Soy dependency to the latest version (supporting proto imports) and update Soy template to use proto imports.
> Update Soy file with new proto import syntax.

- closure/compiler/BUILD
- closure/compiler/closure_base_js_library.bzl
- closure/private/BUILD
- closure/protobuf/BUILD
- closure/stylesheets/BUILD
- closure/testing/BUILD
Added some bzl libraries. The change in closure/compiler/closure_base_js_library.bzl is for deleting a cycle in depsgraph.
> Add bzl libraries

- java/com/google/javascript/jscomp/Diagnostics.java
These are being removed from Closure Compiler
> Remove references to obsolete diagnostics

- java/com/google/javascript/jscomp/JsCheckerClosureCodingConvention.java
isPrivate is being remove from Closure Compiler
> Remove isPrivate reference in advance of its removal

- java/com/google/javascript/jscomp/CheckSetTestOnly.java
- java/com/google/javascript/jscomp/CheckStrictDeps.java
- java/com/google/javascript/jscomp/JsCheckerPassConfig.java
HotSwapCompilerPass and the concept of hostswapping are being removed from Closure Compiler.
> Eliminate deps on HotSwapCompilerPass

- closure/repositories.bzl
- closure/testing/web_test_repositories.bzl
Fixes: https://github.com/bazelbuild/rules_closure/issues/586
> Upgrade rules_go

- closure/private/defs.bzl
> Remove dead code that will be rejected by new bazel versions.

- closure/testing/library/BUILD
- closure/testing/phantomjs_test.bzl
- java/io/bazel/rules/closure/worker/BUILD
- **Various simple cleanups to remove warnings**
- **remove unfurl**
> Various simple cleanups to remove warnings.

- closure/private/base.js
- **Sync base.js to get goog.declareModuleId**
- **typo**
> Sync base.js to get goog.declareModuleId

- MODULE.bazel
Update the rules_webtesting version and bump the rules_scala version to get rid of yanked rules_cc version.
> Update the rules_webtesting version and bump the rules_scala version to get rid of yanked rules_cc version
